# Generated by Django 6.0.1 on 2026-02-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name=50)),
                ('email', models.EmailField(max_length=254, verbose_name=100)),
                ('phoneNo', models.CharField(max_length=15)),
                ('msg', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
