# Generated by Django 6.0.1 on 2026-02-07 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
