# Generated by Django 6.0.1 on 2026-02-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_lead_id_alter_userleadaccess_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='slug',
            field=models.SlugField(blank=True, max_length=300),
        ),
    ]
