# Generated by Django 6.0.1 on 2026-02-17 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientproducts',
            old_name='pname',
            new_name='products_name',
        ),
    ]
