# Generated by Django 6.0.1 on 2026-02-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePagePopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phoneNo', models.CharField(max_length=15)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
