# Generated by Django 6.0.1 on 2026-02-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0002_homepagepopup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagepopup',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
