# Generated by Django 5.2.5 on 2026-02-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_access', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdecryptedlead',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
