# Generated by Django 6.0.1 on 2026-02-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_access', '0002_alter_userdecryptedlead_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdecryptedlead',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
